#pragma once

#include <QString>
#include <QHash>
#include <QMutex>
#include <atomic>

#include "include/database/TrafficStatsRepo.h"

namespace Stats {
    // Reserved profile id for traffic that egressed directly (bypassing every
    // proxy). Negative so it never collides with a real profile id; surfaced in
    // the dashboard as a distinct "Direct" entry rather than a normal outbound.
    constexpr int DIRECT_STAT_PROFILE_ID = -101;

    // Reserved app name for traffic generated by the built-in speed test. Speed
    // tests bypass the clash tracker, so their bytes are credited explicitly and
    // bucketed here as a single synthetic "app" rather than attributed to a real
    // process — the per-app analogue of DIRECT_STAT_PROFILE_ID.
    inline const QString SPEEDTEST_APP_NAME = QStringLiteral("Speedtest");

    // Owns the in-memory minute-bucket accumulators and drives persistence plus
    // tiered downsampling for the traffic-statistics module.
    //
    // The TrafficLooper feeds it per-interval byte deltas (per config now, per
    // app in Phase 2). Deltas accumulate against the current wall-clock minute;
    // when the minute rolls over (or on stop / exit) the bucket is flushed into
    // the separate stats database via Configs::dataManager->trafficStatsRepo. A
    // slow background loop downsamples minute rows older than 48h into the hour
    // tier and prunes hour rows past the configured retention.
    class TrafficStatsManager {
    public:
        // Start the background rollup loop and run a one-shot startup downsample
        // pass. Idempotent; call once after the database manager exists.
        void Init();

        // Accumulate a per-interval delta against a config (profile), mirroring
        // the looper's existing per-profile crediting. Direct traffic uses
        // DIRECT_STAT_PROFILE_ID. No-op for a zero delta.
        void AddConfigDelta(int profileId, long long up, long long down);

        // Accumulate a per-interval delta against an app (process name), keeping
        // the last seen path for icon lookup. Wired in Phase 2 once the core
        // exposes per-process stats; harmless (just unused) until then.
        void AddAppDelta(const QString& processName, const QString& path,
                         long long up, long long down);

        // Persist the in-progress minute bucket. Called on minute rollover, on
        // profile stop, and on exit. No-op when nothing is accumulated.
        void Flush();

        // Snapshot reference metadata for a config so its history stays
        // referenceable after rename/deletion. Called at profile start.
        void SnapshotConfigMeta(int profileId, const QString& name, const QString& groupName,
                                const QString& type, const QString& serverAddress);
        // Ensure the special "Direct" config row exists.
        void EnsureDirectMeta();

    private:
        struct Delta { long long up = 0; long long down = 0; };

        QMutex mu; // guards the accumulators + currentBucket
        QHash<int, Delta> configAccum;
        QHash<QString, Delta> appAccum;
        QHash<QString, QString> appMetaSeen; // process name -> last path written to app_meta
        long long currentBucket = 0; // minute-aligned epoch secs; 0 = nothing yet

        std::atomic<bool> started{false};

        // Caller holds mu: move accumulators into row lists tagged with `bucket`,
        // then clear them.
        void drainLocked(long long bucket, QList<Configs::ConfigTrafficRow>& cfg,
                         QList<Configs::AppTrafficRow>& app);
        // Write drained rows to the repo (call off-lock).
        void writeRows(const QList<Configs::ConfigTrafficRow>& cfg,
                       const QList<Configs::AppTrafficRow>& app);

        // One downsample+prune maintenance pass.
        void runRollupOnce();

        [[nodiscard]] static bool aggregationDisabled();
    };

    extern TrafficStatsManager* trafficStatsManager;
}
